"""Recipe library — runtime read access.

Static, code-resident catalog of foods and recipes. NOT a per-user data source;
this is global reference data shared by every user — the knowledge bank the
meal-logging thread links to for macro tracking.

Source files:
  foods.json             — atomic foods, hand-edited
  recipes.json           — recipe definitions, hand-edited
  recipes.computed.json  — generated by compute.py, has per-serving macros baked in

Runtime reads from foods.json + recipes.computed.json. Each file is mtime-cached:
re-parsed only when its modification time changes. Cost per lookup is one
`stat()` syscall (~10µs).

Public API:
  get_food(id_or_alias)    → Food | None
  get_recipe(id_or_alias)  → ComputedRecipe | None
  list_foods()             → list[Food]
  list_recipes()           → list[ComputedRecipe]
  search_recipes(query)    → list[ComputedRecipe]   (name/alias substring match)
  search_foods(query)      → list[Food]
"""
from __future__ import annotations

import json
from pathlib import Path

from knowledge.recipes.schema import ComputedRecipe, Food

_PKG = Path(__file__).parent
_FOODS_PATH = _PKG / "foods.json"
_COMPUTED_PATH = _PKG / "recipes.computed.json"


def _read_items(path: Path) -> list[dict]:
    """Read a knowledge data file. Accepts a bare JSON list (foods.json) or a
    wrapped `{"recipes": [...]}` object (recipes.computed.json)."""
    raw = json.loads(path.read_text())
    if isinstance(raw, dict):
        # Use `in` (not `or`) so an intentionally-empty list isn't treated as a
        # missing key, and so an unrecognised wrapper fails loudly instead of
        # silently yielding an empty catalog.
        for key in ("recipes", "items"):
            if key in raw:
                return raw[key]
        raise ValueError(
            f"Unrecognised wrapper key in {path.name}: {sorted(raw.keys())} "
            f"(expected 'recipes' or 'items')"
        )
    return raw or []


class _MtimeCache[T: (Food, ComputedRecipe)]:
    """Re-reads `path` only when its mtime changes. Holds parsed entries by id and alias."""

    def __init__(self, path: Path, model: type[T]) -> None:
        self._path = path
        self._model: type[T] = model
        self._mtime: float | None = None
        self._all: list[T] = []
        self._by_alias: dict[str, T] = {}

    def _reload(self) -> None:
        raw = _read_items(self._path)
        items: list[T] = [self._model.model_validate(x) for x in raw]
        by_alias: dict[str, T] = {}
        for item in items:
            by_alias[item.id.lower()] = item
            for alias in item.aliases:
                by_alias[alias.lower()] = item
        self._all = items
        self._by_alias = by_alias

    def _refresh(self) -> None:
        try:
            current = self._path.stat().st_mtime
        except FileNotFoundError:
            raise RuntimeError(
                f"{self._path.name} not found. Run: "
                f"cd server && uv run python -m knowledge.recipes.compute"
            ) from None
        if current != self._mtime:
            # Stamp the mtime *before* reloading: if the file is malformed and
            # _reload() raises, we surface the error on this request but don't
            # re-read/re-parse the broken file on every subsequent one. A fixed
            # file changes its mtime and reloads normally.
            self._mtime = current
            self._reload()

    def lookup(self, id_or_alias: str) -> T | None:
        self._refresh()
        return self._by_alias.get(id_or_alias.lower())

    def all(self) -> list[T]:
        self._refresh()
        return list(self._all)

    def search(self, query: str) -> list[T]:
        """Substring match (case-insensitive) over id, name, and aliases."""
        self._refresh()
        q = query.strip().lower()
        if not q:
            return list(self._all)
        out: list[T] = []
        for item in self._all:
            haystack = [item.id.lower(), item.name.lower(), *(a.lower() for a in item.aliases)]
            if any(q in h for h in haystack):
                out.append(item)
        return out


_foods: _MtimeCache[Food] = _MtimeCache(_FOODS_PATH, Food)
_recipes: _MtimeCache[ComputedRecipe] = _MtimeCache(_COMPUTED_PATH, ComputedRecipe)


def get_food(id_or_alias: str) -> Food | None:
    """Return a food by id or any of its aliases (case-insensitive). None if absent."""
    return _foods.lookup(id_or_alias)


def get_recipe(id_or_alias: str) -> ComputedRecipe | None:
    """Return a computed recipe by id or alias (case-insensitive). None if absent."""
    return _recipes.lookup(id_or_alias)


def list_foods() -> list[Food]:
    return _foods.all()


def list_recipes() -> list[ComputedRecipe]:
    return _recipes.all()


def search_foods(query: str) -> list[Food]:
    return _foods.search(query)


def search_recipes(query: str) -> list[ComputedRecipe]:
    return _recipes.search(query)


__all__ = [
    "get_food",
    "get_recipe",
    "list_foods",
    "list_recipes",
    "search_foods",
    "search_recipes",
    "Food",
    "ComputedRecipe",
]
